### ISSUE TITLE
error on starting

### ISSUE THREAD

**Issue by NerChick** [paulevsGitch/ColorfulFabric#1]
when opening minecraft this error shows up
![image](https://user-images.githubusercontent.com/66223024/112965988-7454ea80-9152-11eb-92ed-6c3e1560aff8.png)

**Comment by NerChick** [comment]
i know its very raw, but im waiting for prgress and very exited about future of this project. Good luck!

**Comment by paulevsGitch** [comment]
It is possible to compile project from [one of old commits](https://github.com/paulevsGitch/ColorfulFabric/commit/b6cdd7116721ec5e3d9b691e30337d3123b0b4dd)

**Comment by paulevsGitch** [comment]
As the current version is under rewriting with completely different algorithm

**Comment by NerChick** [comment]
so colored light will be possible with this mod?

**Comment by paulevsGitch** [comment]
Yes, but the current method of optimisation is not finished and the mod will not work as intended

**Comment by NerChick** [comment]
wdym "will not work as intended"?

**Comment by paulevsGitch** [comment]
I don't remember on what stage was the latest commit, but the world will probably look like normal with strange colored areas instead of normal light

**Comment by paulevsGitch** [comment]
Probably like this or even worse. The reason is incorrect palette packing and unpacking in shader

![2021-03-25_10 20 20](https://user-images.githubusercontent.com/17707380/117715526-0e439480-b1e1-11eb-9ad3-0a33c8fb4ab3.png)

**Comment by paulevsGitch** [comment]
This is how it looked like before this optimisation changes

![2021-03-04_11 43 24](https://user-images.githubusercontent.com/17707380/117715631-3632f800-b1e1-11eb-806b-2db6f9cb7807.png)

**Comment by NerChick** [comment]
so will you fix this?

**Comment by NerChick** [comment]
also will there be forge version?

**Comment by NerChick** [comment]
im so exited for this project cause this is first mod that adds colored light(without shaders)

**Comment by paulevsGitch** [comment]
> so will you fix this?

Yes, when I will have more free time and back to this project again

> will there be forge version?

I'm not making mods for Forge

**Comment by NerChick** [comment]
oh, sadge
