### ISSUE TITLE
Game crashed on start up

### ISSUE THREAD

**Issue by RMSCA** [paulevsGitch/ColorfulFabric#3]
I'm using 2020 mac mini m1, the game will crash everytime I try to start it.

https://pastebin.com/WVmd2LSz

The exact same issue happened on another system with i7-10700 and gtx1650S

Any help is appreciated!

**Comment by paulevsGitch** [comment]
BismuthLib is not compatible with Sodium

**Comment by RMSCA** [comment]
it worked after removing sodium, thank you very much!
