### ISSUE TITLE
Sodium issue

### ISSUE THREAD

**Issue by Papagemabodi** [paulevsGitch/ColorfulFabric#4]
I tried to launch bismuthlib with sodium, it crashes. When I remove Sodium it launches well, but I can play without sodium because without it my average fps goes to 5
[crash-2023-07-05_17.26.06-client.txt](https://github.com/paulevsGitch/BismuthLib/files/11959171/crash-2023-07-05_17.26.06-client.txt)

**Comment by Papagemabodi** [comment]
and the main thing is when I installed phosphor(it fully rewrites light engine, intuitically it will not be compatible with bismuthlib, but it launches)

**Comment by paulevsGitch** [comment]
It is not compatible with Sodium
