### ISSUE TITLE
Game crashed with create mod

### ISSUE THREAD

**Issue by mattervisualizer** [paulevsGitch/ColorfulFabric#6]
Its sad, that your mod incompatible with create, i think this will very cool to fix this

Fabric Loader 0.14.21
Fabric API 0.76.0
Minecraft 1.19.2
BismuthLib Alpha 0.1.0

Crash-report: [crash-2023-08-04_15.36.31-client.txt](https://github.com/paulevsGitch/BismuthLib/files/12260808/crash-2023-08-04_15.36.31-client.txt)
Lastet log: [latest.log](https://github.com/paulevsGitch/BismuthLib/files/12260921/latest.log)

**Comment by paulevsGitch** [comment]
In logs it tells about incompatibility with sodium:
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_761::cf_onRenderChunkLayer with priority 1000 cannot inject into net/minecraft/class_761::method_3251(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLnet/minecraft/class_1159;)V merged by me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> bismuthlib.mixins.json:LevelRendererMixin from mod bismuthlib -> Prepare Injections ->  -> handler$bem000$bismuthlib$cf_onRenderChunkLayer(Lnet/minecraft/class_1921;Lnet/minecraft/class_4587;DDDLnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]

which is duplicate of issue #4

**Comment by mattervisualizer** [comment]
Thanks
